#!/bin/sh
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="PHP5 FastCGI Process Manager"
NAME=php5-fpm
DAEMON=/usr/sbin/$NAME
DAEMON_ARGS="--fpm-config /data/webstack/config/php/php-fpm.conf -c /data/webstack/config/php/php.ini"
PIDFILE=/data/log/php/php5-fpm.pid
TIMEOUT=30
SCRIPTNAME=/etc/init.d/$NAME
